name = ""
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ["blog", "dark"]
features = [
  "minimalistic blog",
  "social icons",
  "editable colors"
]

[author]
  name = "Grimtail"
  homepage = ""
