baseURL = 'https://github.com/GrimtailsProjects/GrimtailsProjects'
languageCode = 'en-us'
title = 'My Projects and Stuff im interested in :3'
theme = "m10c"

author = "Grimtail"
description = "Just a guy like me and you"
avatar = "static/logo.webp"